### ISSUE TITLE
Необходимо более подробное ТЗ

### ISSUE THREAD

**Issue by leotsarev** [lanit-summer/cleangames#1]
Дмитрий, необходимо более подробное ТЗ.
Для начала думаю необходимо описать как выглядит чекин (самый простой) и как выглядит админка (самая простая) из расчета, что мы пока поддерживаем одну организацию (Чистые Игры) и один конкретный квест или игру (27 июля которая).

Cc: @lanit-summer/cleangames

**Comment by svtarasov** [comment]
Дмитрий добавил кейсы использования приложения на вики.

**Comment by mtr1305** [comment]
Коллеги. я тут подумал, что сейчас существует уже несколько мобильных приложений, в которых можно делать чекины (Вконтакте, Телеграм), которые при этом могут отдавать  данные наружу. В частности на той неделе прочитал, что в Телеграме запустили возможность делать ботов, которые дают дополнительную функциональность сервису. Т.е. можно сделать своего бота от Чистых игр и через него чекинить. При этом там видны чужие чекины, можно чекиниться в них. 

Может быть нам стоит не заниматься своим мобильным приложением, а сосретодочиться на бэкенде и бэкофисе системы. 

На данный момент, прямо сейчас на практике мы используем приложение ВК и сайт, который все это отображает. Базы нет, т.е. база это посты в вк. Вот бэкенд с базой нужен, чтобы мы могли полноценно оперировать данными.

**Comment by svtarasov** [comment]
Тут как сказать, у нас, мне кажется, большая часть народу пришла в проект чтобы писать на Java. Но в любом случае, база с бэкэндом подразумевается как часть задачи

**Comment by mtr1305** [comment]
так бэкенд на джава это разве не самое то? или нужен именно андроид сдк?
