### ISSUE TITLE
Сделать view для регистрации/авторизации пользователя

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/cleangames#10]
Описание из кейса:
Устанавливаю мобильное приложение на телефон. Авторизуюсь через авторизацию приложения (регистрируюсь, если нет регистрации: Имя, фамилия, почта, пароль, повторить пароль). Могу авторизоваться через соц. сети (Вконтакте, Фейсбук).

**Comment by svtarasov** [comment]
Есть кнопка «Забыл пароль?». Это в момент авторизации. При нажатии на эту кнопку, то тебе открывается экран, на котором текст «введите свой емейл» и поле для емейла, кнопка «Отправить». Если я ввел свой емейл и нажал Отправить, то появляется надпись «Ваш пароль выслан вам в почту». Проверяю почту, получаю там письмо с моим паролем. (лучше использовать уже готовые модули для авторизации, регистрации, авторизации через соц. сети и восстановления паролей).

**Comment by leotsarev** [comment]
А зачем нам вообще пароль?
Давайте на начальном этапе только через соцсети.
Дмитрий?
3 июля 2015 г. 9:25 AM пользователь "Sergey Tarasov" <
notifications@github.com> написал:

**Comment by Mikelle** [comment]
Я займусь этим.

**Comment by lada-gagina** [comment]
Если только соцсети для начала, то думаю, что я и одна справлюсь.

**Comment by svtarasov** [comment]
Сделано. Закрыто
