### ISSUE TITLE
Сделать View для чекина игрока

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/cleangames#15]
На карте отмечены локации для данного проекта. Я могу нажать пальцем на экран на карте, поставить новую отметку (чекин), появляется диалоговое окно с вопросом «Добавить новую отметку на карте?», Да/Нет. Нажимаю Да. Появляется новая отметка. Я нажимаю на эту отметку , появляется попап, в котором есть разделы:

Фото
Комментарий
Параметры в данном проекте (Мусор вперемешку, Металл, Пластик и т.д.)
Фото: могу добавить одно или несколько фото, снять с камеры или выбрать из галереи существующих на мобильнике фото. Могу удалить добавленные фото нажав на крестик.

Комментарий: печатаю текст какой захочу.

Параметры: Проставляю сколько и какого мусора я собрал в данной отметке. Нажимаю + или - чтобы увеличить или уменьшить значение параметра, или ввожу цифру в поле. Нажимаю «Сохранить».

**Comment by svtarasov** [comment]
Фото пока не принципиально.

**Comment by AlexMoskvin** [comment]
сделал

**Comment by AlexMoskvin** [comment]
Без фото сделал

**Comment by svtarasov** [comment]
Виды мусора следующие:
Пластик
Металл
Стекло
Смешанный мусор
Батарейки

все это будем брать из базы, так что на вьюшке нужно предусмотреть 5 полей ввода  - по полю на каждый вид мусора.

**Comment by AlexMoskvin** [comment]
Сделано

**Comment by svtarasov** [comment]
Закрыто
