### ISSUE TITLE
Реализовать меню по кнопке

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/cleangames#19]
Разобраться как реализуется данный элемент и приделать его в какой-нибудь вьюшке. Данный элемент должен быть доступен на всех вьюшках, за исключением вьюшки авторизации. 
Меню должно содержать следующие пункты:
- Игра
- Команда
- Рейтинг 
- Карта

**Comment by malchkate** [comment]
Мы же договорились не выезжающее?

**Comment by leotsarev** [comment]
+1

On Tue, Jul 7, 2015 at 10:52 AM, malchkate notifications@github.com wrote:

> Мы же договорились не выезжающее?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lanit-summer/cleangames/issues/19#issuecomment-119108626
> .

## 

С уважением, Леонид

**Comment by svtarasov** [comment]
Леня. я правильно понимаю, что меню показывается по стандартной кнопке в андройде и оно выезжающее?

**Comment by leotsarev** [comment]
Мы договорились что по стандартной кнопке, если сложно сделать выезжающее,
сделать просто вьюшку

2015-07-07 15:02 GMT+03:00 Sergey Tarasov notifications@github.com:

> Леня. я правильно понимаю, что меню показывается по стандартной кнопке в
> андройде и оно выезжающее?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lanit-summer/cleangames/issues/19#issuecomment-119182096
> .

## 

С уважением, Леонид

**Comment by svtarasov** [comment]
Поменял заголовок

**Comment by malchkate** [comment]
Сделано.
