### ISSUE TITLE
Постановка задачи. Обсуждение используемых технологий

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/cleangames#2]
Всем привет!

Давайте обсудим, что будем делать и на чем будем делать. Нам нужно примерно следующее:
1) Некоторое мобильное приложение, которое позволяет чекиниться на карте и складывает инфу о чекинах в какую-нибудь базу данных. (Нам рекомендуется использовать Java + Android Studio, но если большинство захочет что-то другое - не возбраняется).

2) База данных, в которой будет храниться информация о чекинах. Соответственно, нужно хранилище, где эта база будет развернута.

Более подробную информацию по приложению мы надеемся получить  от нашего заказчика Дмитрия чуть позже.
Для примерного понимания, что мы будем делать - ссылка на сайт Чистых игр в Петергофе: http://www.cleangames.ru/

Пожалуйста, пишите в комментариях, какие технологии вы хотите использовать. По результатам опроса будем принимать решение.

**Comment by mtr1305** [comment]
Я вывесил кейсы использования системы. 

У меня есть хостинг, на котором можно развернуть базу,  могу выдать логин пароль от хостинг панели тому, кто этим будет заниматься.

**Comment by svtarasov** [comment]
Отлично, спасибо. Возникает вопрос - у кого из участников есть желание заниматься базой данных? Пожалуйста, желающие отпишитесь.

**Comment by AlexMoskvin** [comment]
Я бы хотел заниматься чем-то связанным с JAVA так как изучаю язык, нужен опыт.

**Comment by AlexMoskvin** [comment]
Будет ли у нас встреча 1 июля?

**Comment by mtr1305** [comment]
Я 1-го июля буду в Москве. До 5-го июля. Смогу встретится 6-го июля у вас.
Но 1 июля готов быть через скайп
Пн, 29 июня 2015 г. в 13:31, AlexMoskvin notifications@github.com:

**Comment by AlexMoskvin** [comment]
Жду слов от руководителей проекта...

**Comment by AlexMoskvin** [comment]
Нет желания встретиться завтра?

**Comment by svtarasov** [comment]
1 июля в 11-00 в аудитории 405 будет общая встреча для участников Летней Школы. Там все с  друг с другом еще раз познакомятся, и далее уже разойдемся по своим аудиториям.

Алек,  я предлагаю для начала взглянуть на те кейсы использования приложения, которые Дмитрий выложил на вики. Также можно подумать, над тем какие задачи можно на основе этих кейсов сформировать. Если есть какие-то конкретные вопросы по задачам приложения - я думаю, мы их завтра обсудим. Если тебе хочется Java, то тогда можно заняться разработкой мобильного приложения.

**Comment by svtarasov** [comment]
Дмитрий, скажите, а что установлено на вашем хостинге?

**Comment by mtr1305** [comment]
mySQL
это имеется ввиду?

**Comment by svtarasov** [comment]
Ага

**Comment by malchkate** [comment]
Добрый вечер! А ноутбук завтра же желателен или завтра только обсуждаем структуру проекта?

**Comment by didenko-ilia** [comment]
Я буду заниматься базой данных. Выдайте пожалуйста информацию о хостинге.

**Comment by svtarasov** [comment]
Закрываю обсуждение в связи с появлением новой рубрики #14
