### ISSUE TITLE
Спроектировать структуру базы данных

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/cleangames#3]
Посмотреть кейсы использования на вики, и то что есть на сайте http://cleangames.ru/

**Comment by svtarasov** [comment]
Вера может пообсуждать

**Comment by svtarasov** [comment]
Илья привет, пароль я тебе пошлю. Возможную структуру обсудите с Верой пожалуйста

**Comment by didenko-ilia** [comment]
Структура базы: https://www.gliffy.com/go/publish/image/8483045/L.png
Связь обоначена цветами, чтобы не загромождать картинку

**Comment by leotsarev** [comment]
GarbageCollect — неверно. Это не «сбор», это «сдача» или «передача» GagbageTransfer
Кстати про координаты — в SQL server есть тип geography — он как раз для этого сделан.

**Comment by didenko-ilia** [comment]
Обновил название, добавил параметры для чекина.
Для координат можно использовать Point (geography в phpMyAdmin нет), но я не уверен какой способ будет удобнее.

**Comment by leotsarev** [comment]
А блин я забыл, что у нас не MS SQL.

2015-07-08 14:10 GMT+03:00 didenko-ilia notifications@github.com:

> Обновил название, добавил параметры для чекина.
> Для координат можно использовать Point (geography в phpMyAdmin нет), но я
> не уверен какой способ будет удобнее.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lanit-summer/cleangames/issues/3#issuecomment-119543458
> .

## 

С уважением, Леонид

**Comment by didenko-ilia** [comment]
https://www.gliffy.com/go/publish/image/8483045/L.png
Добавил комментарии к локации, обновил названия (Checkin, CheckinItem, Transfer, TransferItem)
