### ISSUE TITLE
Сделать прототип приложения с картой

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/cleangames#4]
Сделать прототип приложения с картой, на которой отображается локация.

**Comment by svtarasov** [comment]
+Белозерцева Даша

**Comment by svtarasov** [comment]
- Коновалова Ирина

**Comment by svtarasov** [comment]
- Чудова Марина

**Comment by svtarasov** [comment]
Ребята есть старый теркомовский проект.  Какие-то вещи с картой можно попробовать посмотреть https://code.google.com/p/android-geocaching/w/list

**Comment by malchkate** [comment]
Добрый день! 
У нас возникло несколько вопросов!
1)Откуда появляется список игроков, которые "выбрали проект"?Регистрация заранее?(Кейс 1, добавление команды)
2)Обозначать ли каким-то цветом "неполную"очистку локации?(оранжевым например)
3) И самый главный вопрос. Сказано, что организатор формирует команды, но так же по Кейсам у игрока , то есть у любого пользователя есть возможность создать новую команду. Так ли необходимо администратору создавать команды? Или если все-таки администратор создает, то нужно ли игрокам в эту раскладку вмешиваться?

**Comment by svtarasov** [comment]
Катя, посмотри пожалуйста на #9

**Comment by svtarasov** [comment]
Сделано. Закрываю
