### ISSUE TITLE
Сделать UI пользовательского чекина на карте

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/cleangames#5]
Разобраться. как делается чекин на карте с полем "Комментарий".

**Comment by svtarasov** [comment]
Алек, посмотри пожалуйста, тут нужно немного поинвестигировать вопрос

**Comment by AlexMoskvin** [comment]
Хорошо.Есть какие-нибудь точки начальные, откуда можно  информацию взять?
завтра во сколько встреча?

**Comment by svtarasov** [comment]
Завтра встреча в 11-15  - будет скрам. По поводу карты можно попробовать посмотреть что-то здесь https://code.google.com/p/android-geocaching/w/list

**Comment by AlexMoskvin** [comment]
А в какой аудитории?

**Comment by svtarasov** [comment]
В аудитории 2408

**Comment by AlexMoskvin** [comment]
https://xakep.ru/2014/07/21/java-spy-servlet/
http://habrahabr.ru/company/mediagates/blog/145411/

Здесь пара ссылок про работы с чекинами и картами.

**Comment by AlexMoskvin** [comment]
http://stackoverflow.com/questions/13696620/google-maps-android-api-v2-authorization-failure

Настройка подключения google maps к android приложению

**Comment by AlexMoskvin** [comment]
Можно закрыть . Сделано
