### ISSUE TITLE
Разобраться с кодировками на сервере

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/cleangames#55]
Не отображаются русские символы

**Comment by svtarasov** [comment]
Оценка 10 чел*час

**Comment by didenko-ilia** [comment]
Проблема была на локальном сервере из-за стандартной кодировки. Решаеться добавлением строчки " URIEncoding="UTF-8" " в server.xml, в <Connector>. На api.cleangames.ru проблемы нет.
