### ISSUE TITLE
Выбрать готовый модуль для авторизации в мобильном приложении

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/cleangames#6]
Чтобы поддерживал ВКонтакте, Фейсбук

**Comment by mtr1305** [comment]
Я знаю проект ulogin, посмотрите
Вт, 30 июня 2015 г. в 17:40, Sergey Tarasov notifications@github.com:

**Comment by svtarasov** [comment]
Посмотреть как выбранный модуль будет работать в рамках #10

**Comment by lada-gagina** [comment]
Посмотрела uLogin, Logzilla, socialauth-android и ASNE(https://github.com/gorbin/ASNE). Пока самым простым вариантом кажется uLogin. Пробую сделать прототип приложения с авторизацией. Пока авторизация будет только через соц.сети, да?

**Comment by svtarasov** [comment]
Да, попробуй сделать с авторизацией через соц сети, Тут еще Миша занимается #10  Так что посмотрите вместе пожалуйста, как вам тут можно объединиться. А регистрация как будет работать?

**Comment by svtarasov** [comment]
Сделано. Закрыто
