### ISSUE TITLE
View с картой: добавить ленту событий, таблицу с рейтингом команд

### ISSUE THREAD

**Issue by svtarasov** [lanit-summer/cleangames#9]
Надо уточнить. как считается рейтинг команд

**Comment by malchkate** [comment]
А на какой вьюшке надо делать рейтинг команд? На ленте надо было? или где?
Ленту же мы решили не делать.

**Comment by malchkate** [comment]
Ленту же мы решили не делать.

**Comment by svtarasov** [comment]
Да на текущий момент это должна быть вьюшка с игровой картой. Для рейтинга будет отдельная вьюшка, на которую переходим из элемента с меню.

**Comment by svtarasov** [comment]
Закрываю как сделанное
